// AIProvider abstraction (§50, §81). Hard rules encoded structurally, not
// just by convention:
//  - Every AIResponse carries the source records it was generated from and a
//    generatedAt timestamp, so the UI can always render "AI-generated, based
//    on: [...]" (§52) — callers cannot construct a response without them.
//  - safetyFlag surfaces high-risk content (§25/§91) so the UI can prioritize
//    "seek care now" messaging over the AI's own text.
//  - This module never receives more than the minimal patient data a given
//    feature needs (§50 data minimization) — callers pass pre-selected
//    records in, this module does not query the database itself.
//  - No patient data reaches a real vendor unless ENABLE_AI=true AND a
//    provider/key is configured (§53) — the mock is what runs otherwise.

export interface AISourceRecord {
  type: string;
  id: string;
  label: string;
}

export interface AIResponse {
  text: string;
  sources: AISourceRecord[];
  generatedAt: string;
  safetyFlag: "NONE" | "SUGGEST_PROFESSIONAL_REVIEW" | "URGENT_CARE_RECOMMENDED";
  disclaimer: string;
}

const STANDARD_DISCLAIMER =
  "This summary is generated by AI to help you understand your own records. It is not a diagnosis " +
  "and does not replace advice from a qualified clinician.";

const HIGH_RISK_TERMS = [
  "chest pain",
  "can't breathe",
  "cannot breathe",
  "difficulty breathing",
  "unconscious",
  "loss of consciousness",
  "severe bleeding",
  "suicidal",
  "suicide",
  "severe allergic reaction",
  "anaphylaxis",
];

export function screenForHighRisk(text: string): boolean {
  const lower = text.toLowerCase();
  return HIGH_RISK_TERMS.some((term) => lower.includes(term));
}

export interface AIProvider {
  summarizeTimeline(records: AISourceRecord[], rangeLabel: string): Promise<AIResponse>;
  explainLabResult(record: AISourceRecord & { resultText: string }): Promise<AIResponse>;
  summarizeDocument(record: AISourceRecord & { extractedText: string }): Promise<AIResponse>;
  prepareForVisit(records: AISourceRecord[]): Promise<AIResponse>;
}

// Template-based mock — no external network call, no patient data leaves the
// process. This exists so every AI-feature UI (§51) can be built and tested
// now; a real provider (Claude via the Anthropic API, behind AI_PROVIDER env)
// is a Phase 2 wiring task, not a UI change.
class MockAIProvider implements AIProvider {
  async summarizeTimeline(records: AISourceRecord[], rangeLabel: string): Promise<AIResponse> {
    const safetyFlag = screenForHighRisk(records.map((r) => r.label).join(" "))
      ? "URGENT_CARE_RECOMMENDED"
      : "NONE";
    return {
      text:
        records.length === 0
          ? `No recorded health events were found for ${rangeLabel}.`
          : `Over ${rangeLabel}, ${records.length} health event(s) were recorded, including ` +
            `${records
              .slice(0, 3)
              .map((r) => r.label)
              .join(", ")}${records.length > 3 ? ", and others" : ""}. Review the full timeline for details ` +
            `and discuss any changes with your healthcare provider.`,
      sources: records,
      generatedAt: new Date().toISOString(),
      safetyFlag,
      disclaimer: STANDARD_DISCLAIMER,
    };
  }

  async explainLabResult(record: AISourceRecord & { resultText: string }): Promise<AIResponse> {
    return {
      text:
        `"${record.label}" is a laboratory measurement. Your recorded result was: ${record.resultText}. ` +
        `Reference ranges vary by laboratory and individual context — ask your provider what this specific ` +
        `result means for you.`,
      sources: [record],
      generatedAt: new Date().toISOString(),
      safetyFlag: "NONE",
      disclaimer: STANDARD_DISCLAIMER,
    };
  }

  async summarizeDocument(record: AISourceRecord & { extractedText: string }): Promise<AIResponse> {
    const safetyFlag = screenForHighRisk(record.extractedText) ? "URGENT_CARE_RECOMMENDED" : "NONE";
    return {
      text: `Document "${record.label}" was processed. Review the extracted fields below and confirm any that should become part of your structured health record.`,
      sources: [record],
      generatedAt: new Date().toISOString(),
      safetyFlag,
      disclaimer: STANDARD_DISCLAIMER,
    };
  }

  async prepareForVisit(records: AISourceRecord[]): Promise<AIResponse> {
    return {
      text:
        "Questions you might ask your doctor based on your selected records: Has anything changed since my " +
        "last visit? Are my current medications still appropriate? Are there any results I should be " +
        "watching more closely?",
      sources: records,
      generatedAt: new Date().toISOString(),
      safetyFlag: "NONE",
      disclaimer: STANDARD_DISCLAIMER,
    };
  }
}

let instance: AIProvider | null = null;

// ENABLE_AI + a configured AI_PROVIDER/AI_API_KEY would select a real vendor
// implementation here (§53/§81) — none is wired up in this phase, so this
// always returns the mock regardless of the flag. The flag still governs
// whether AI-feature UI is shown at all (see featureFlags.ai), independent
// of which provider answers the call.
export function getAIProvider(): AIProvider {
  if (!instance) instance = new MockAIProvider();
  return instance;
}
