import Anthropic from "@anthropic-ai/sdk";

// AIProvider abstraction (§50, §81). Hard rules encoded structurally, not
// just by convention:
//  - Every AIResponse carries the source records it was generated from and a
//    generatedAt timestamp, so the UI can always render "AI-generated, based
//    on: [...]" (§52) — callers cannot construct a response without them.
//  - safetyFlag surfaces high-risk content (§25/§91) so the UI can prioritize
//    "seek care now" messaging over the AI's own text. The real provider
//    screens BOTH the input data and the model's own output text — the
//    model might mention something risky even if asked not to interpret,
//    and what ultimately matters is what the patient is about to read.
//  - This module never receives more than the minimal patient data a given
//    feature needs (§50 data minimization) — callers pass pre-selected
//    records in, this module does not query the database itself.
//  - No patient data reaches a real vendor unless ENABLE_AI=true AND
//    AI_PROVIDER=anthropic with AI_API_KEY set (§53) — the mock is what
//    runs otherwise, and is always what runs in this repo's own test suite.

export interface AISourceRecord {
  type: string;
  id: string;
  label: string;
}

export interface AIResponse {
  text: string;
  sources: AISourceRecord[];
  generatedAt: string;
  safetyFlag: "NONE" | "SUGGEST_PROFESSIONAL_REVIEW" | "URGENT_CARE_RECOMMENDED";
  disclaimer: string;
}

export const STANDARD_DISCLAIMER =
  "This summary is generated by AI to help you understand your own records. It is not a diagnosis " +
  "and does not replace advice from a qualified clinician.";

const HIGH_RISK_TERMS = [
  "chest pain",
  "can't breathe",
  "cannot breathe",
  "difficulty breathing",
  "unconscious",
  "loss of consciousness",
  "severe bleeding",
  "suicidal",
  "suicide",
  "severe allergic reaction",
  "anaphylaxis",
];

export function screenForHighRisk(text: string): boolean {
  const lower = text.toLowerCase();
  return HIGH_RISK_TERMS.some((term) => lower.includes(term));
}

export interface AIProvider {
  summarizeTimeline(records: AISourceRecord[], rangeLabel: string): Promise<AIResponse>;
  explainLabResult(record: AISourceRecord & { resultText: string }): Promise<AIResponse>;
  summarizeDocument(record: AISourceRecord & { extractedText: string }): Promise<AIResponse>;
  prepareForVisit(records: AISourceRecord[]): Promise<AIResponse>;
}

// Template-based mock — no external network call, no patient data leaves the
// process. This is what runs whenever a real vendor isn't explicitly
// configured, and is what this repo's own test suite always exercises.
class MockAIProvider implements AIProvider {
  async summarizeTimeline(records: AISourceRecord[], rangeLabel: string): Promise<AIResponse> {
    const safetyFlag = screenForHighRisk(records.map((r) => r.label).join(" "))
      ? "URGENT_CARE_RECOMMENDED"
      : "NONE";
    return {
      text:
        records.length === 0
          ? `No recorded health events were found for ${rangeLabel}.`
          : `Over ${rangeLabel}, ${records.length} health event(s) were recorded, including ` +
            `${records
              .slice(0, 3)
              .map((r) => r.label)
              .join(", ")}${records.length > 3 ? ", and others" : ""}. Review the full timeline for details ` +
            `and discuss any changes with your healthcare provider.`,
      sources: records,
      generatedAt: new Date().toISOString(),
      safetyFlag,
      disclaimer: STANDARD_DISCLAIMER,
    };
  }

  async explainLabResult(record: AISourceRecord & { resultText: string }): Promise<AIResponse> {
    return {
      text:
        `"${record.label}" is a laboratory measurement. Your recorded result was: ${record.resultText}. ` +
        `Reference ranges vary by laboratory and individual context — ask your provider what this specific ` +
        `result means for you.`,
      sources: [record],
      generatedAt: new Date().toISOString(),
      safetyFlag: "NONE",
      disclaimer: STANDARD_DISCLAIMER,
    };
  }

  async summarizeDocument(record: AISourceRecord & { extractedText: string }): Promise<AIResponse> {
    const safetyFlag = screenForHighRisk(record.extractedText) ? "URGENT_CARE_RECOMMENDED" : "NONE";
    return {
      text: `Document "${record.label}" was processed. Review the extracted fields below and confirm any that should become part of your structured health record.`,
      sources: [record],
      generatedAt: new Date().toISOString(),
      safetyFlag,
      disclaimer: STANDARD_DISCLAIMER,
    };
  }

  async prepareForVisit(records: AISourceRecord[]): Promise<AIResponse> {
    return {
      text:
        "Questions you might ask your doctor based on your selected records: Has anything changed since my " +
        "last visit? Are my current medications still appropriate? Are there any results I should be " +
        "watching more closely?",
      sources: records,
      generatedAt: new Date().toISOString(),
      safetyFlag: "NONE",
      disclaimer: STANDARD_DISCLAIMER,
    };
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Anthropic (Claude) — the real vendor implementation. Selected only when
// AI_PROVIDER=anthropic and AI_API_KEY is set (see getAIProvider() below).
// ─────────────────────────────────────────────────────────────────────────

const DEFAULT_MODEL = "claude-haiku-4-5-20251001"; // fast + inexpensive, right fit for short factual summaries
const MAX_OUTPUT_TOKENS = 500;
const REQUEST_TIMEOUT_MS = 20_000;

// Every system prompt ends with this. Encoded once so a change to the
// safety boundary can't accidentally apply to only some of the four
// features — see §23/§25.
const SAFETY_BOUNDARY =
  "You are not a medical professional. Never diagnose, prescribe, recommend starting/stopping/changing any " +
  "medication, or claim certainty about a diagnosis. Base your response only on the information given to you " +
  "in this request — never invent facts, dates, or values that aren't present. If the provided information " +
  "includes any sign of a medical emergency — chest pain, severe or worsening difficulty breathing, loss of " +
  "consciousness, uncontrolled or severe bleeding, signs of a severe allergic reaction, or any expression of " +
  "suicidal intent — your response must begin by clearly and calmly telling the patient to seek urgent or " +
  "emergency medical care right away, before anything else.";

const TIMELINE_SUMMARY_SYSTEM =
  "You help a patient understand their own recorded health history in plain, calm language. Summarize only " +
  "the events provided — do not add interpretation beyond a pattern already evident in the data itself (e.g. " +
  "a value trending up across several entries). Keep your response to 2-4 sentences.\n\n" + SAFETY_BOUNDARY;

const LAB_EXPLAIN_SYSTEM =
  "You explain laboratory test results to the patient who had them, in plain language a non-clinician can " +
  "follow. Explain generally what the test measures and what the provided result and reference range (if any) " +
  "indicate in plain terms. Do not tell the patient their result is 'good', 'bad', or 'dangerous', or " +
  "otherwise pass clinical judgment beyond noting whether it falls inside or outside a stated reference range. " +
  "Always close by recommending they discuss the result with their clinician. Keep your response to 2-4 " +
  "sentences.\n\n" + SAFETY_BOUNDARY;

const DOCUMENT_SUMMARY_SYSTEM =
  "You summarize a medical document's extracted text for the patient who uploaded it. Cover, only where " +
  "present in the text: document type, date, provider, key findings or results, medications mentioned, and " +
  "any follow-up mentioned. If something isn't present in the text, omit it rather than guessing. End with " +
  "one or two questions the patient might ask their doctor about this document. Keep your response " +
  "concise.\n\n" + SAFETY_BOUNDARY;

const VISIT_PREP_SYSTEM =
  "You generate 3-5 thoughtful, specific questions a patient could ask their doctor, based only on the health " +
  "records provided. Do not suggest what the answers might be. Do not diagnose or interpret the records beyond " +
  "what's needed to motivate a relevant question. Return the questions as a short list.\n\n" + SAFETY_BOUNDARY;

// Minimal shape this module actually uses from the SDK client — real
// `Anthropic` instances satisfy it structurally, and tests can inject a
// lightweight fake without needing to match the SDK's full type surface.
export interface AnthropicClientLike {
  messages: {
    create(params: {
      model: string;
      max_tokens: number;
      temperature: number;
      system: string;
      messages: { role: "user"; content: string }[];
    }): Promise<{ content: { type: string; text?: string }[] }>;
  };
}

export class AnthropicAIProvider implements AIProvider {
  private client: AnthropicClientLike;
  private model: string;

  constructor(client?: AnthropicClientLike) {
    if (client) {
      this.client = client;
    } else {
      const apiKey = process.env.AI_API_KEY;
      if (!apiKey) {
        throw new Error("AI_API_KEY must be set when AI_PROVIDER=anthropic. See ENVIRONMENT.md.");
      }
      this.client = new Anthropic({ apiKey, timeout: REQUEST_TIMEOUT_MS });
    }
    this.model = process.env.AI_MODEL || DEFAULT_MODEL;
  }

  async summarizeTimeline(records: AISourceRecord[], rangeLabel: string): Promise<AIResponse> {
    if (records.length === 0) {
      return {
        text: `No recorded health events were found for ${rangeLabel}.`,
        sources: [],
        generatedAt: new Date().toISOString(),
        safetyFlag: "NONE",
        disclaimer: STANDARD_DISCLAIMER,
      };
    }
    const eventLines = records.map((r) => `- [${r.type}] ${r.label}`).join("\n");
    const userPrompt = `Summarize the following recorded health events from ${rangeLabel}:\n\n${eventLines}`;
    return this.generate(TIMELINE_SUMMARY_SYSTEM, userPrompt, records, eventLines);
  }

  async explainLabResult(record: AISourceRecord & { resultText: string }): Promise<AIResponse> {
    const userPrompt = `Test: ${record.label}\nResult: ${record.resultText}`;
    return this.generate(LAB_EXPLAIN_SYSTEM, userPrompt, [record], `${record.label} ${record.resultText}`);
  }

  async summarizeDocument(record: AISourceRecord & { extractedText: string }): Promise<AIResponse> {
    const userPrompt = `Document title: ${record.label}\n\nExtracted text:\n${record.extractedText}`;
    return this.generate(DOCUMENT_SUMMARY_SYSTEM, userPrompt, [record], record.extractedText);
  }

  async prepareForVisit(records: AISourceRecord[]): Promise<AIResponse> {
    if (records.length === 0) {
      return {
        text: "Add some records to your timeline first, and this will suggest questions based on them.",
        sources: [],
        generatedAt: new Date().toISOString(),
        safetyFlag: "NONE",
        disclaimer: STANDARD_DISCLAIMER,
      };
    }
    const eventLines = records.map((r) => `- [${r.type}] ${r.label}`).join("\n");
    const userPrompt = `Recent health records:\n\n${eventLines}`;
    return this.generate(VISIT_PREP_SYSTEM, userPrompt, records, eventLines);
  }

  private async generate(
    systemPrompt: string,
    userPrompt: string,
    sources: AISourceRecord[],
    inputTextForScreening: string
  ): Promise<AIResponse> {
    const inputRisk = screenForHighRisk(inputTextForScreening);

    let text: string;
    try {
      const response = await this.client.messages.create({
        model: this.model,
        max_tokens: MAX_OUTPUT_TOKENS,
        temperature: 0.2,
        system: systemPrompt,
        messages: [{ role: "user", content: userPrompt }],
      });
      const block = response.content.find((b) => b.type === "text");
      text = block?.text?.trim() ?? "";
      if (!text) throw new Error("Empty response from AI provider.");
    } catch (err) {
      // Never let vendor error details (which can include request internals)
      // reach the client — the route handler turns this into the §65
      // "temporarily unavailable" message. Log server-side only.
      console.error("[ai:anthropic] request failed:", err instanceof Error ? err.message : err);
      throw new Error("AI provider request failed.");
    }

    // Screen the model's actual output, not just the input — what matters
    // is what the patient is about to read (§25).
    const outputRisk = screenForHighRisk(text);

    return {
      text,
      sources,
      generatedAt: new Date().toISOString(),
      safetyFlag: inputRisk || outputRisk ? "URGENT_CARE_RECOMMENDED" : "NONE",
      disclaimer: STANDARD_DISCLAIMER,
    };
  }
}

let instance: AIProvider | null = null;

// ENABLE_AI gates whether the AI feature UI/routes are reachable at all
// (see featureFlags.ai) — independent of which provider answers the call.
// This selects the provider itself: AnthropicAIProvider only when
// AI_PROVIDER=anthropic AND AI_API_KEY is set; the mock otherwise, so a
// misconfigured or partially-configured environment fails safe rather than
// throwing on every request.
export function getAIProvider(): AIProvider {
  if (!instance) {
    instance =
      process.env.AI_PROVIDER === "anthropic" && process.env.AI_API_KEY
        ? new AnthropicAIProvider()
        : new MockAIProvider();
  }
  return instance;
}

// Test-only: forces the next getAIProvider() call to reconstruct the
// provider instead of reusing the module-level singleton.
export function _resetAIProviderForTests(): void {
  instance = null;
}
